name: Deploy TodoList

on:
  push:
    branches:
      - master
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build app
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run:  npm i
      - run:  npm run build

      - uses: akhileshns/heroku-deploy@v3.10.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ptp-todolist"
          heroku_email: "paulodetarsopoma@gmail.com"
          usedocker: true